name: Android-CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build, Sign, and Upload APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Generate APK (unsigned)
        run: ./gradlew assembleRelease

      - name: Show APK files
        run: find app/build/outputs/ -type f

      - name: Download Keystore File
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > keystore.jks

      - name: Sign APK
        run: |
          $ANDROID_SDK_ROOT/build-tools/34.0.0/apksigner sign \
            --ks keystore.jks \
            --ks-key-alias ${{ secrets.KEY_ALIAS }} \
            --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
            --key-pass pass:${{ secrets.KEY_PASSWORD }} \
            --out app/build/outputs/apk/release/app-release-signed.apk \
            app/build/outputs/apk/release/app-release-unsigned.apk

      - name: Install App Center CLI
        run: npm install -g appcenter-cli

      - name: Upload APK to App Center
        run: |
          appcenter distribute release \
          --app "majidsiddiqui1997/majidApplication" \
          --token "${{ secrets.APP_CENTER_TOKEN }}" \
          --file app/build/outputs/apk/release/app-release-signed.apk \
          --group "Testers"

      - name: Upload APK Artifact (Optional)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-signed
          path: app/build/outputs/apk/release/app-release-signed.apk
