name: Android-CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build, Sign, and Upload APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # Decode Keystore
      - name: Download and Decode Keystore
        run: |
          mkdir -p app
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > app/release-key.jks

      # Set environment variables
      - name: Set up environment for signing
        run: |
          echo "KEYSTORE_FILE=release-key.jks" >> $GITHUB_ENV
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV

      # Build signed APK
      - name: Build Signed APK
        run: ./gradlew assembleRelease

      - name: Show APK files
        run: find app/build/outputs/ -type f

      - name: Check APK File Permissions
        run: ls -l app/build/outputs/apk/release/app-release.apk

      - name: Install App Center CLI
        run: npm install -g appcenter-cli@latest

      - name: Upload APK to App Center
        run: |
          echo "Uploading APK to App Center..."
          export DEBUG=appcenter-cli:*
          appcenter distribute release \
          --app "majidsiddiqui1997/majidApplication" \
          --token "${{ secrets.APP_CENTER_TOKEN }}" \
          --file app/build/outputs/apk/release/app-release.apk \
          --group "collaborator" \
          --debug

      - name: Upload APK Artifact (Optional)
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk
