name: Android-CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # - name: Run SonarQube analysis
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   run: ./gradlew sonar --info

      # - name: Build the project
      #   run: ./gradlew assembleDebug

      # - name: Run unit tests
      #   run: ./gradlew testDebugUnitTest

      - name: Generate APK
        run: ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk

      - name: Install App Center CLI
        run: npm install -g appcenter-cli

      - name: Upload APK to App Center
        run: >
          appcenter distribute release
          --app "${{ secrets.APP_CENTER_OWNER_NAME }}/${{ secrets.APP_CENTER_APP_NAME }}"
          --token "${{ secrets.APP_CENTER_TOKEN }}"
          --file app/build/outputs/apk/release/app-release.apk
          --group "Testers"
